### ISSUE TITLE
Prevent bootloop manually

### ISSUE THREAD

**Issue by timea-techgirl** [neoblackxt/MIUIAnesthetist#1]
Hello,

I'm trying to remove apps from a Nexus 5 MIUI ROM available on the official site. Is there a way to prevent bootloop without xposed and this module? Something that can be done manually?

Thanks!

**Comment by neoblackxt** [comment]
Hi，
threre is a way，[Solve the frozen rebound of MIUI8](http://www.programmersought.com/article/2168890696/). Method 2. Don’t be confused by the title, the methed can also prevent bootloop.

**Comment by timea-techgirl** [comment]
Hey! Thanks a lot for the reply. I'm not a programmer, so I don't know how to do it. Does it take a lot of time?

I'll be using my phone for another 5 years and I wished I could have MIUI ROM. I deleted apps one by one, I deleted apps directly from the ROM zip file...etc. Nothing worked. It ended in a bootloop. I've been asking people about this since 2 years and nobody answered.

So, thank you again for answering. :)

**Comment by neoblackxt** [comment]
My pleasure. I suggest you ask a ROM developer for help on XDA. I am not a ROM developer pro and I don’t have a Nexus 5, so I can’t test it. If you want me to do this, I would like charger you $5 for it. I don’t provide any warranty and refund. Modifying ROMs one by one is a endless job, it must be limited.

**Comment by timea-techgirl** [comment]
Hey! Alright, I will ask again on XDA. If nobody responds, I'll ask you again. :)

**Comment by neoblackxt** [comment]
Closed for no reply for too long time.

**Comment by timeakesmarky** [comment]
Hey I wrote you on telegram.
