### ISSUE TITLE
在Edexposed上启用模块后，出现一系列问题。

### ISSUE THREAD

**Issue by LinkAiR** [neoblackxt/MIUIAnesthetist#2]
机型mi8，开发版系统9.5.30，在Edexposed上启用模块后，出现一系列问题：
1.默认桌面变成未选择，导致无法正常回到桌面；
2.所有apk文件无法打开，显示“没有找到应用打开该类型的文件”；
3.长按音量键无法唤醒小爱同学。

**Comment by neoblackxt** [comment]
v1.0和v2.0版本都会出现上述问题吗？

**Comment by LinkAiR** [comment]
> v1.0和v2.0版本都会出现上述问题吗？

之前只试了2.0版本，现在降级到1.0之后以上问题没有再发生。。

**Comment by neoblackxt** [comment]
为了反劫持小米应用商店，我对MIUI系统的版本类型进行了临时修改，可能是临时修改为国际版期间发生了一些副作用。下一个版本修复此问题。咕~

**Comment by neoblackxt** [comment]
[船新版本](https://github.com/neoblackxt/MIUIAnesthetist/releases/tag/v2.1)v2.1

**Comment by LinkAiR** [comment]
> [船新版本](https://github.com/neoblackxt/MIUIAnesthetist/releases/tag/v2.1)v2.1

特来反馈：船新版本已解决上述所有问题~[手动滑稽]
