### ISSUE TITLE
3.0版本暂时不支持太极，需要提交，谢谢

### ISSUE THREAD

**Issue by star2k** [neoblackxt/MIUIAnesthetist#5]
http://admin.taichi.cool/

**Comment by neoblackxt** [comment]
Hi, 感谢关注，
开启太极阳模，更新至436版本及以上，按需添加应用： 应用包管理组件、安全中心、设置。[RADEME](https://github.com/neoblackxt/MIUIAnesthetist/blob/master/README.md)

**Comment by star2k** [comment]
好的，感谢大佬提供这么好的工具，除了去除小米应用市场默认项意外，还有其他什么功能，从太极阳下点击，看不到设置项。


readme描述中的“修改此模块中的install.sh文件，将你想要移除的应用的所在目录填写在REPLACE=""中，一行一个，格式参照文件中上面几行的例子。修改完成后在Magisk Manager中安装它或在recovery模式下刷入它”，

这是怎么操作的，如何OPEN，感觉说的是一个zip包？


------------------ 原始邮件 ------------------
发件人: "Neo"<notifications@github.com>;
发送时间: 2019年7月20日(星期六) 中午1:49
收件人: "neoblackxt/MIUIAnesthetist"<MIUIAnesthetist@noreply.github.com>;
抄送: "Jim"<wqxxsjc@gmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [neoblackxt/MIUIAnesthetist] 3.0版本暂时不支持太极，需要提交，谢谢 (#5)




Hi, 感谢关注，
 开启太极阳模，更新至436版本及以上，按需添加应用： 应用包管理组件、安全中心、设置。RADEME

**Comment by neoblackxt** [comment]
对对对，就是zip。我认为用MT管理器打开&修改可能是个不错的选择。

**Comment by neoblackxt** [comment]
功能就是README中的那些功能，没有其他的。
为什么没有软件界面，说出来你可能感到奇怪，我没有特意学习过安卓应用开发，不会做界面，而且预计长期内也不会去做界面。
而做这个东西是因为某天我的小米手机被莫名其妙的偷偷安装了两个游戏，安装来源正是小米应用商店，又想起它还劫持谷歌应用商店，太流氓了，忍无可忍！于是一怒之下就做了这个东西。我不管是因为我误触还是小米的后门，总之它惹到我了，那我就得怼它。

**Comment by star2k** [comment]
安装麻醉事后，如果删除小米市场，重启手机后不会卡米了？


 
---原始邮件---
发件人: "Neo"<notifications@github.com>
发送时间: 2019年7月20日(星期六) 下午4:07
收件人: "neoblackxt/MIUIAnesthetist"<MIUIAnesthetist@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"Jim"<wqxxsjc@gmail.com>;
主题: Re: [neoblackxt/MIUIAnesthetist] 3.0版本暂时不支持太极，需要提交，谢谢 (#5)



功能就是README中的那些功能，没有其他的。
 为什么没有软件界面，说出来你可能感到奇怪，我没有特意学习过安卓应用开发，不会做界面，而且预计长期内也不会去做界面。
 而做这个东西是因为某天我的小米手机被莫名其妙的偷偷安装了两个游戏，安装来源正是小米应用商店，又想起它还劫持谷歌应用商店，太流氓了，忍无可忍！于是一怒之下就做了这个东西。我不管是因为我误触还是小米的后门，总之它惹到我了，那我就得怼它。

**Comment by neoblackxt** [comment]
不会，但你最好别删，非要删务必遵从README中的操作
